on:
  push:
    branches: main
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      
name: 🚚 Get latest code
      uses: actions/checkout@v2

      
name: Use Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: "16.13.0"

      
name: 🔨 Build Project
      env:
        REACT_APP_API_KEY: ${{ secrets.REACT_APP_FIREBASE_API_KEY }}
        REACT_APP_AUTH_DOMAIN: ${{ secrets.REACT_APP_FIREBASE_AUTH_DOMAIN }}
        REACT_APP_PROJECT_ID: ${{ secrets.REACT_APP_FIREBASE_PROJECT_ID }}
        REACT_APP_STORAGE_BUCKET: ${{ secrets.REACT_APP_FIREBASE_STORAGE_BUCKET }}
        REACT_APP_MESSAGING_SENDER_ID: ${{ secrets.REACT_APP_FIREBASE_MESSAGING_SENDER_ID }}
        REACT_APP_APP_ID: ${{ secrets.REACT_APP_FIREBASE_APP_ID }}
        REACT_APP_DATABASE_URL: ${{ secrets.REACT_APP_FIREBASE_DATABASE_URL }}
      run: |
        cd frontend
        npm install
        npm run build

      
name: List output files
      run: find frontend/build/ -print

      
name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.1.0
      with:
        server: ftp.mattiasbellan.ca
        username: reboot-ftp@rebootfitness.mattiasbellan.ca
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: frontend/build/
